### ISSUE TITLE
Spelling error in the name of a judge

### ISSUE THREAD

**Issue by OpenFirstNL** [openstate/open-rechtspraak#44]
[mr. S.M. Kingsma](https://openrechtspraak.nl/person/916b3c44-bcf1-440e-bcd2-4d951585106f) has an extra s in it compared to the information on [rechtspraak.nl](https://namenlijst.rechtspraak.nl/#!/details/c7iWRJUvsHysTRY4URGq9py_lmbFO0P3).
The correct spelling is Kingma. Where did the extra 's' come from?

**Comment by siccovansas** [comment]
This was most likely an error on rechtspraak.nl. We copied it and probably don't expect names to change (which they do, e.g., also when some people marry) and thus don't check that. We should indeed check for name changes (and also show the old name?).

**Comment by Jonakemon** [comment]
@OpenFirstNL this should now be fixed!
