### ISSUE TITLE
Data opvragen via de Open Data API

### ISSUE THREAD

**Issue by jcsdesterke** [openstate/open-rechtspraak#52]
Hallo,

Ook al weet ik dat dit niet de repo is die hier over gaat, maar dat jullie er vast genoeg over weten stel ik mijn vraag gewoon hier.

Ik probeer uitspraken uit een specifiek jaar op te vragen op het rechtsgebied strafrecht.
Nu wil ik ook kunnen filteren op enkele zoektermen zoals zwijgrecht of zwijgende verdachte.
Hoe stuur ik deze zoektermen mee in mijn request?

Wat ik nu heb is http://data.rechtspraak.nl/uitspraken/zoeken?date=2022-01-01&date=2023-01-01&subject=http%3A%2F%2Fpsi.rechtspraak.nl%2Frechtsgebied%23strafrecht&type=Uitspraak&return=DOC

Alvast bedankt.

Jan de Sterke

**Comment by Jonakemon** [comment]
Hoi Jan, volgens mij kan https://data.rechtspraak.nl niet filteren op zoektermen (aldus de technische documentatie https://www.rechtspraak.nl/Uitspraken/paginas/open-data.aspx). 

Ik heb zelf in het verleden wel eens gebruik gemaakt van de API die achter https://uitspraken.rechtspraak.nl zit: https://uitspraken.rechtspraak.nl/#!/resultaat?zoekterm=zwijgrecht&inhoudsindicatie=zt0&publicatiestatus=ps1&sort=Relevance. Daar kan je wel zoeken, maar is er weer geen documentatie beschikbaar.

Via curl zou je deze request kunnen doen (laat vooral weten als je een voorbeeld wilt in een andere taal, zoals Python):
```
curl "https://uitspraken.rechtspraak.nl/api/zoek" \
-X POST \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
--data-raw '{"StartRow":0,"PageSize":10,"ShouldReturnHighlights":true,"ShouldCountFacets":true,"SortOrder":"Relevance","SearchTerms":[{"Term":"zwijgrecht","Field":"AlleVelden"}],"Contentsoorten":[],"Rechtsgebieden":[],"Instanties":[],"DatumPublicatie":[],"DatumUitspraak":[],"Advanced":{"PublicatieStatus":"AlleenGepubliceerd"},"CorrelationId":"96536b09d9a24c1bba3f20090650d2ca","Proceduresoorten":[]}'
```

**Comment by jcsdesterke** [comment]
Hoi,

Bedankt voor je (ontzettend) snelle reactie.
Ik was nu inderdaad bezig om de request die op uitspraken.rechtspraak.nl gedaan wordt met de zoekmachine na te bootsen. Omdat daar inderdaad zoektermen aan meegegeven worden. De resultaten kan ik dan op een handige manier combineren op basis van de ECLI's.

Ik werk in JavaScript en ga met je voorbeeld aan de slag. Alle informatie is welkom dus als je nog meer voorbeelden/ervaringen hebt, hoor ik het graag.

**Comment by Jonakemon** [comment]
Hier is een voorbeeld met [axios](https://www.npmjs.com/package/axios):

```javascript
const axios = require('axios')

const data = {
    "StartRow": 0,
    "PageSize": 10,
    "ShouldReturnHighlights": true,
    "ShouldCountFacets": true,
    "SortOrder": "Relevance",
    "SearchTerms": [{
        "Term": "zwijgrecht",
        "Field": "AlleVelden"
    }],
    "Contentsoorten": [],
    "Rechtsgebieden": [],
    "Instanties": [],
    "DatumPublicatie": [],
    "DatumUitspraak": [],
    "Advanced": {
        "PublicatieStatus": "AlleenGepubliceerd"
    },
    "Proceduresoorten": []
}

const response = axios({
    method: 'post',
    headers: {
        "Accept": "application/json",
        "Content-Type": "application/json"
    },
    url: "https://uitspraken.rechtspraak.nl/api/zoek",
    data: data
}).then((response) => {
    console.log(response.data)
})
```

Ik sluit de issue; mocht je nog meer vragen hebben, stel ze dan gerust! Ik kan niet beloven dat er altijd zo snel wordt gereageerd als vanavond.

**Comment by fpatje85** [comment]
@Jonakemon ,

Ik ben momenteel bezig met de uitspraken.rechtspraak api.
Tot nu toe werkt het, maar ik wil graag nog een vanaf datum (Uitspraakdatum) willen ingeven vanaf waar hij moet zoeken.

Ik heb meerdere dingen geprobeerd, maar als ik ook maar iets achter de DatumUitspraak zet krijg ik geen response. Weet jij hier meer over?

**Comment by Jonakemon** [comment]
Hi @fpatje85! Voor de uitspraken.rechtspraak.nl api kan je in 'real time' testen welke velden wat doen door naar de pagina te gaan en via de 'developer tools' tab te kijken wat er gebeurd als je datums intikt. Daaruit haal ik dat je op deze manier kan zoeken op basis van een datumrange:

```
{
    "StartRow": 0,
    "PageSize": 10,
    "ShouldReturnHighlights": true,
    "ShouldCountFacets": true,
    "SortOrder": "Relevance",
    "SearchTerms": [],
    "Contentsoorten": [],
    "Rechtsgebieden": [],
    "Instanties": [],
    "DatumPublicatie": [],
    "DatumUitspraak": [],
    "Advanced": {
        "PublicatieStatus": "AlleenGepubliceerd",
        "UitspraakdatumRange": {
            "From": "01-01-2024",
            "To": "01-02-2024"
        }
    },
    "CorrelationId": "d78c86d7056d4c5faaef75d59c27e1a5",
    "Proceduresoorten": []
}
```

Een alternatieve optie is het gebruiken van data.rechtspraak.nl. Hier is een voorbeeld waarin je kan zoeken op basis van uitspraakdatum: https://data.rechtspraak.nl/uitspraken/zoeken?date=2011-05-01&date=2011-05-30. Ik heb dat voorbeeld gehaald uit de 'technische documentatie' die op rechtspraak.nl gepubliceerd is: https://www.rechtspraak.nl/Uitspraken/Paginas/Open-Data.aspx (onderaan -> technische documentatie).

Daarin staat ook hoe je daarna per zaak meer informatie kan ophalen. Let op dat data.rechtspraak.nl en uitspraken.rechtspraak.nl andere APIs zijn. Dus als de een niet werkt, kan je altijd de andere proberen!
