### ISSUE TITLE
ECLI numbers related to judge

### ISSUE THREAD

**Issue by ThijmenDam** [openstate/open-rechtspraak#53]
Hi! Is it possible to retrieve the ECLI numbers associated with a particular judge via your API, e.g. similar to what you provide on your website [here](https://openrechtspraak.nl/person/6af372c8-d583-4224-9cc4-806168cf6fd6)?

PS: I'm using your API for my master's thesis. If you're interested, I can share it whenever it's finished 🙂

**Comment by Jonakemon** [comment]
Currently it's not. We've got some development time planned next week; I'll try to squeeze this feature request in! If that's too late, please let me know so we won't spend time on it either.

**Comment by ThijmenDam** [comment]
Yes, that would be great if you have the time! Thank you.

**Comment by Jonakemon** [comment]
Hi @ThijmenDam, the feature is online! I.e.: https://openrechtspraak.nl/api/v1/person/6af372c8-d583-4224-9cc4-806168cf6fd6/verdicts

You can check the API documentation for more information!

**Comment by ThijmenDam** [comment]
Awesome! I'll look into it either tonight or tomorrow night.

**Comment by ThijmenDam** [comment]
Thanks @Jonakemon, looks great :-)
